### ISSUE TITLE
Can't import to eclipse

### ISSUE THREAD

**Issue by KcMeterCEC** [littlevgl/proj_pc#1]
Hi, your GUI is very fascinating , so i want to explore it.

Then i follow your guide[ step by step](http://littlev.hu/index.php/getting-started/run-on-pc/) .

When i want to import project to eclipse, **the eclipse warn can't find project file!**

And i find your ".gitignore" file is ignored ".cproject" and ".settings" , i think it's why i can't import...

Please fix the bug.Thanks!

**Comment by kisvegabor** [comment]
Hi!

I removed those files from .gitignore and pushed them. Thank you for reporting the issue.

Today I started a new website with and released an improved version of the library. I recommend you to use the new versions: http://gl.littlev.hu

**Comment by KcMeterCEC** [comment]
Thanks!

Your new website is awesome!

**Comment by kisvegabor** [comment]
Thanks. I hope it is useful too :)

Please keep me informed if you have any other problem with the PC simulator.
